name: Print CPU Architecture ARM64

on: 
  workflow_dispatch: null

jobs:
  print-architecture:
    runs-on: [self-hosted, ubuntu-20.04, arm64]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Print CPU Architecture
      run: uname -m
