name: Release - Ubuntu 20.04 - ARM
'on':
  workflow_dispatch: null
  push:
    tags:
    - v*
    - test-release-*
jobs:
  build:
    runs-on: ['self-hosted', 'arm64', 'ubuntu-20.04']
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Grant Access
      run: git config --global --add safe.directory "$PWD"
    - name: rustup
      run: rustup default stable
    - name: set-env DEB_UPSTREAM_VERSION
      shell: bash
      run: echo "DEB_UPSTREAM_VERSION=$(ci/tag-name.sh)" >> $GITHUB_ENV
    - name: set-env SAPLING_VERSION
      shell: bash
      run: echo "SAPLING_VERSION=$(ci/tag-name.sh)" >> $GITHUB_ENV
    - name: Create .deb
      working-directory: ./eden/scm
      run: ${{ format('VERSION={0} make deb', env.DEB_UPSTREAM_VERSION) }}
    - name: Rename .deb
      working-directory: ./eden/scm
      run: ${{ format('mv sapling_{0}_amd64.deb sapling_{0}_amd64.Ubuntu20.04.deb', env.DEB_UPSTREAM_VERSION, env.DEB_UPSTREAM_VERSION) }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-20.04-arm64
        path: ./eden/scm/sapling_*.deb
